### ISSUE TITLE
Conda-forge package

### ISSUE THREAD

**Issue by mattijn** [vega/vl-convert#29]
Would it be possible to release this package as well on conda-forge? That would make it a bit more accessible for users:
```cmd
conda/mamba install vl-convert-python
```

**Comment by jonmmease** [comment]
Yes, it should be pretty straightforward. It should be able to follow the pattern of `vegafusion-embed` pretty closely: https://github.com/conda-forge/vegafusion-python-embed-feedstock.

Let me know if anyone else is interested in getting started on it, otherwise I'll try to work on it over the next week or two.

**Comment by jonmmease** [comment]
WIP recipe in https://github.com/conda-forge/staged-recipes/pull/20956

**Comment by jonmmease** [comment]
Initial packages have been published: https://anaconda.org/conda-forge/vl-convert-python

Still TODO before closing this issue:
 - [ ] osx-arm64 support
 - [ ] Python 3.11 support

**Comment by jonmmease** [comment]
osx-arm64 packages are now available!
